from ubuntu:latest

MAINTAINER gerbil@cons.io

ARG squid
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y
RUN apt install -y \
    autoconf \
    automake \
    build-essential \
    gfortran \
    git \
    libffi-dev \
    libleveldb-dev \
    liblmdb-dev \
    libmysqlclient-dev \
    libsnappy1v5  \
    libsqlite3-dev \
    libssl-dev \
    libyaml-dev \
    lsb-release \
    pkg-config \
    sudo \
    tmux \
    tzdata \
    wget \
    x11-xserver-utils \
    zlib1g-dev
